version: '3.8'
services:
  api:
    image: node:14
    working_dir: /app
    volumes:
      - .:/app
    command: npm install && npm start
    environment:
      - DB_HOST=db-mysql
      - DB_PORT=3306
      - DB_NAME=api
      - DB_USER=root
      - DB_PASSWORD=123456
    ports:
      - "8080:8080"
    depends_on:
      - db-mysql

  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"